import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// Exclude "buffer" from builtins so it's not treated as external
const filteredBuiltins = builtins.filter(mod => mod !== "buffer");

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	inject: ["./polyfills.js"],
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		"global": "globalThis", // ✅ Required for `buffer` compatibility
	},
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...filteredBuiltins
		],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}